apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-demo.fullname" . }}
  labels:
    {{- include "k8s-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "k8s-demo.selectorLabels" . | nindent 4 }}
