apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-node-port
  namespace: k8s-demo
  labels:
    app: k8s-demo
spec:
  type: NodePort
  ports:
    - name: k8s-demo-server
      port: 8081 # service port
      targetPort: 8080 # container port
      nodePort: 30007
