apiVersion: v1
kind: Service
metadata:
  name: k8s-demo
  namespace: k8s-demo
  labels:
    app: k8s-demo
spec:
  ports:
    # single port
    - port: 8081 # service port
      targetPort: 8080 # container port
    # multiple ports
    - port: 8082
      targetPort: 8082
    # different protocols
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
  selector:
    app: k8s-demo
